### ISSUE TITLE
Task for training statistics

### ISSUE THREAD

**Issue by parkourtheory-admin** [parkourtheory/datapipe#113]
Collect training data (loss, validation, etc) from Record and generate training statistics

**Comment by parkourtheory-admin** [comment]
Getting the following error just from the import statement `from pymongo import MongoClient`

```
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    main()
  File "/Users/justin/Documents/projects/datapipe/utils.py", line 96, in wrapper_timer
    value = func(*args, **kwargs)
  File "main.py", line 28, in main
    pipe = build(cfg)
  File "/Users/justin/Documents/projects/datapipe/pipeline.py", line 125, in build
    pipe.append(cl[0][1](cfg)) # index 0 is class name and index 1 is object
  File "/Users/justin/anaconda3/envs/ml/lib/python3.8/site-packages/pymongo/mongo_client.py", line 632, in __init__
    for entity in host:
```

Closing this and will make this into a separate script in Search.
